import { defineConfig } from 'tsdown'

const packageId = 'dsh-plugin-memory-knowledge'
const clientExternals = new Set([
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
])

export default defineConfig([{
  name: packageId,
  entry: {
    index: 'src/index.ts',
    schema: 'src/schema.ts',
    canonical: 'src/canonical.ts',
    projection: 'src/projection.ts',
    initialize: 'src/initialize.ts',
    service: 'src/service.ts',
    provider: 'src/provider.ts',
    'evidence-pack': 'src/evidence-pack.ts',
    inventory: 'src/inventory.ts',
    'candidate-generation': 'src/candidate-generation.ts',
    'source-records': 'src/source-records.ts',
    'source-analysis': 'src/source-analysis.ts',
    'source-analysis-service': 'src/source-analysis-service.ts',
    'source-analysis-provider': 'src/source-analysis-provider.ts',
    'source-relations': 'src/source-relations.ts',
    'source-relation-query': 'src/source-relation-query.ts',
    'source-relations-service': 'src/source-relations-service.ts',
    'source-relations-provider': 'src/source-relations-provider.ts',
    'source-symbols': 'src/source-symbols.ts',
    'source-symbol-query': 'src/source-symbol-query.ts',
    'source-symbols-service': 'src/source-symbols-service.ts',
    'source-symbols-provider': 'src/source-symbols-provider.ts',
    'wiki-model': 'src/wiki-model.ts',
    'wiki-task': 'src/wiki-task.ts',
    'wiki-agent-service': 'src/wiki-agent-service.ts',
    'wiki-agent-provider': 'src/wiki-agent-provider.ts',
    'wiki-catalog': 'src/wiki-catalog.ts',
    'wiki-material': 'src/wiki-material.ts',
    'knowledge-version': 'src/knowledge-version.ts',
    'conversation-extraction': 'src/conversation-extraction.ts',
    'conversation-extraction-consumer': 'src/conversation-extraction-consumer.ts',
    'inventory-provider': 'src/inventory-provider.ts',
    recall: 'src/recall.ts',
    tools: 'src/tools.ts',
    'ui-contract': 'src/ui-contract.ts',
    'remote-contract': 'src/remote-contract.ts',
    gateway: 'src/gateway.ts',
    cli: 'src/bin.ts',
  },
  outDir: 'lib',
  format: 'esm',
  platform: 'node',
  deps: {
    alwaysBundle: ['@deepseek-ai/dsh-atomic-write', '@deepseek-ai/dsh-home-paths'],
  },
  dts: false,
  clean: true,
  sourcemap: false,
}, {
  name: `${packageId}/client`,
  entry: { client: 'src/client/index.ts' },
  outDir: 'lib',
  format: 'cjs',
  platform: 'browser',
  target: 'es2024',
  dts: false,
  clean: false,
  sourcemap: false,
  deps: {
    neverBundle: (specifier: string) => clientExternals.has(specifier),
    alwaysBundle: (specifier: string) => !clientExternals.has(specifier),
  },
  outputOptions: {
    entryFileNames: 'client.js',
    banner: `window.__ModuleLoader__.load({ id: ${JSON.stringify(packageId)}, factory: (require) => {`,
    footer: 'return module.exports; } });',
    intro: 'var module = { exports: {} }; var exports = module.exports;',
  },
}])
